# Runtime stage: Use JRE for smaller image
FROM eclipse-temurin:17-jre-jammy
WORKDIR /app

# Copy the executable JAR (assumes name like backend-1.0.0.jar)
COPY target/*.jar backend.jar

EXPOSE 8080
#ENV WELCOME_MSG="Welcome DevOps Team in Opstree"

ENTRYPOINT ["java", "-jar", "backend.jar"]
